"""
Real-time Journal Feedback Service (Issue #6)

Provides 3 types of feedback as the user types in their journal:

1. INSIGHT - Connecting patterns across multiple journal entries
   "Your mural entry and childhood memory both center on feeling seen
    without words. That thread is growing."

2. BLINDSPOT - Recurring pattern causing suffering the user may not see
   "You've mentioned cancelling plans 4 times this month. Each time
    you felt relief, then guilt."

3. BREAKTHROUGH - A potentially life-changing realization
   "What if the reason you keep seeking validation is that you never
    got it from the one person who mattered?"

The feedback is generated by GPT-4o-mini using the current journal text
plus context from past entries. The LLM decides which type of feedback
is most appropriate (or returns none if the text is too short/generic).
"""

import json
import logging
from typing import Optional, Dict

from openai import OpenAI
from app.core.config import cfg as c

logger = logging.getLogger(__name__)

# Use the same OpenAI client config as the rest of the app
_client = None

def _get_client() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(api_key=c.OPENAI_API_KEY)
    return _client


FEEDBACK_MODEL = "gpt-4o-mini"

SYSTEM_PROMPT = """You are an empathic journal companion embedded in a mental health app called ReWire. 
Your job is to provide ONE piece of real-time feedback on the user's current journal entry.

You have access to their past journal entries for context. Use them to find patterns, connections, and themes.

You MUST respond with EXACTLY one of these 3 feedback types, or "none" if no meaningful feedback is possible:

1. INSIGHT — Connect a pattern or theme across multiple entries (current + past).
   - Only use this if you can genuinely connect the current entry to something from a past entry.
   - Be specific about which entries you're connecting and what the thread is.
   - Tone: warm, observational, like a thoughtful friend noticing something.
   
2. BLINDSPOT — Identify a recurring pattern that may be causing suffering without the user realizing it.
   - Only use this if you see the same behavior/thought appearing 3+ times across entries.
   - Be gentle but direct. Name the pattern without judgment.
   - Tone: caring honesty, like a trusted advisor pointing something out kindly.
   
3. BREAKTHROUGH — Surface a potentially transformative realization or reframing.
   - Only use this rarely, when the user's words contain the seed of a major insight they haven't fully articulated.
   - Frame it as a "what if" question, not a statement.
   - Tone: electric, thought-provoking, but never pushy.

RULES:
- Return ONLY valid JSON. No markdown, no backticks, no preamble.
- Keep feedback to 1-2 sentences maximum. Be concise and impactful.
- If the current text is too short, too generic, or you can't find anything meaningful, return type "none".
- NEVER be preachy, clinical, or condescending.
- NEVER diagnose or label the user.
- NEVER use therapy jargon like "cognitive distortion" or "schema".
- Write like a wise, warm friend — not a therapist.
- Match the emotional register of the user's writing.
- If the user is in pain, acknowledge it before offering insight.

JSON format:
{"feedback_type": "insight|blindspot|breakthrough|none", "feedback_text": "Your 1-2 sentence feedback here"}
"""


def generate_journal_feedback(
    current_text: str,
    past_context: str,
) -> Optional[Dict[str, str]]:
    """
    Generate real-time feedback on a journal entry.
    
    Args:
        current_text: The text the user is currently writing
        past_context: Formatted string of past journal entries for context
        
    Returns:
        Dict with "feedback_type" and "feedback_text", or None if no feedback
    """
    if not current_text or len(current_text.strip()) < 30:
        return None
    
    client = _get_client()
    
    # Build the user message
    user_parts = []
    
    if past_context and past_context.strip():
        user_parts.append(
            "PAST JOURNAL ENTRIES (for context — use these to find patterns):\n"
            f"{past_context}\n\n"
            "---\n\n"
        )
    else:
        user_parts.append(
            "No past journal entries available yet.\n\n"
            "---\n\n"
        )
    
    user_parts.append(
        "CURRENT ENTRY (what the user is writing right now):\n"
        f"{current_text}\n\n"
        "---\n\n"
        "Provide ONE piece of feedback as JSON. "
        "If you can connect this to a past entry, use 'insight'. "
        "If you see a recurring harmful pattern across 3+ entries, use 'blindspot'. "
        "If their words contain a seed of a major realization, use 'breakthrough'. "
        "If none of these apply, return type 'none'."
    )
    
    user_msg = "".join(user_parts)
    
    try:
        resp = client.chat.completions.create(
            model=FEEDBACK_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_msg},
            ],
            temperature=0.7,
            max_tokens=200,
        )
        
        content = resp.choices[0].message.content.strip()
        
        # Clean up potential markdown wrapping
        if content.startswith("```"):
            content = content.split("\n", 1)[-1]  # Remove first line
            if content.endswith("```"):
                content = content[:-3]
            content = content.strip()
        
        # Parse JSON response
        result = json.loads(content)
        
        feedback_type = result.get("feedback_type", "none")
        feedback_text = result.get("feedback_text", "")
        
        # Validate feedback type
        if feedback_type not in ("insight", "blindspot", "breakthrough", "none"):
            logger.warning(f"[journal_insights] Invalid feedback_type: {feedback_type}")
            return None
        
        if feedback_type == "none" or not feedback_text:
            return None
        
        logger.info(f"[journal_insights] Generated {feedback_type} feedback ({len(feedback_text)} chars)")
        
        return {
            "feedback_type": feedback_type,
            "feedback_text": feedback_text.strip(),
        }
        
    except json.JSONDecodeError as e:
        logger.warning(f"[journal_insights] Failed to parse LLM response as JSON: {e}")
        return None
    except Exception as e:
        logger.error(f"[journal_insights] LLM call failed: {e}")
        return None
